import axios from "axios";

const BASE_URL = "https://movienew.cybersoft.edu.vn";

const BASE_MOVIE_URL = `${BASE_URL}/api/QuanLyPhim`;
const BASE_MOVIE_BY_THEATER_URL = `${BASE_URL}/api/QuanLyRap`;
const BASE_USER_URL = `${BASE_URL}/api/QuanLyNguoiDung`;
const BASE_TICKET_URL = `${BASE_URL}/api/QuanLyDatVe`;
const BASE_CINEMA_URL = `${BASE_URL}/api/QuanLyRap`;
const TOKEN_CYBERSOFT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCBTw6FuZyAwNCIsIkhldEhhblN0cmluZyI6IjA1LzAzLzIwMjMiLCJIZXRIYW5UaW1lIjoiMTY3Nzk3NDQwMDAwMCIsIm5iZiI6MTY1NDEwMjgwMCwiZXhwIjoxNjc4MTIyMDAwfQ.FunqYipkHrCbBATBzuJXyjGpZZxDekx1oY2qxW3_yfw";

const AXIOS_INSTANCE_GENERATOR = (BASE_URL, token = TOKEN_CYBERSOFT) =>
  axios.create({
    baseURL: BASE_URL,
    headers: { TokenCybersoft: token },
  });

const MOVIE_AXIOS_INSTANCE = AXIOS_INSTANCE_GENERATOR(BASE_MOVIE_URL);
const MOVIE_BY_THEATER_AXIOS_INSTANCE = AXIOS_INSTANCE_GENERATOR(
  BASE_MOVIE_BY_THEATER_URL
);
const USER_AXIOS_INSTANCE = AXIOS_INSTANCE_GENERATOR(BASE_USER_URL);

const BOOKING_TICKET_AXIOS_INSTANCE = AXIOS_INSTANCE_GENERATOR(BASE_TICKET_URL);

export {
  TOKEN_CYBERSOFT,
  MOVIE_AXIOS_INSTANCE,
  USER_AXIOS_INSTANCE,
  MOVIE_BY_THEATER_AXIOS_INSTANCE,
  BOOKING_TICKET_AXIOS_INSTANCE,
};
